// <auto-generated />
using System;
using API_Farm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Farm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240918130108_AddSeedersAnimal")]
    partial class AddSeedersAnimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_Farm.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("int")
                        .HasColumnName("animal_type_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.ToTable("animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2020, 3, 25),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Lucy",
                            WeightKg = 438.62657639839387
                        },
                        new
                        {
                            Id = 2,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2024, 9, 9),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Name = "Bonnie",
                            WeightKg = 219.54965794091456
                        },
                        new
                        {
                            Id = 3,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2020, 8, 31),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Iris",
                            WeightKg = 420.51139919537428
                        },
                        new
                        {
                            Id = 4,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2023, 1, 12),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Kristi",
                            WeightKg = 0.83653782322055303
                        },
                        new
                        {
                            Id = 5,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2020, 12, 29),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Adrian",
                            WeightKg = 6.4142383345377114
                        },
                        new
                        {
                            Id = 6,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2022, 1, 24),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Name = "Lynn",
                            WeightKg = 308.56136261113556
                        },
                        new
                        {
                            Id = 7,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2021, 10, 2),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Florence",
                            WeightKg = 74.364587261547882
                        },
                        new
                        {
                            Id = 8,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2021, 9, 22),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Name = "Felicia",
                            WeightKg = 188.92464313107868
                        },
                        new
                        {
                            Id = 9,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2024, 2, 3),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Angel",
                            WeightKg = 287.44698976716546
                        },
                        new
                        {
                            Id = 10,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2021, 7, 27),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Name = "Bridget",
                            WeightKg = 452.34844486821532
                        },
                        new
                        {
                            Id = 11,
                            AnimalTypeId = 5,
                            BirthDate = new DateOnly(2023, 11, 1),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Name = "Elena",
                            WeightKg = 445.04361864688292
                        },
                        new
                        {
                            Id = 12,
                            AnimalTypeId = 1,
                            BirthDate = new DateOnly(2023, 12, 17),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Cornelius",
                            WeightKg = 362.92321205662529
                        },
                        new
                        {
                            Id = 13,
                            AnimalTypeId = 2,
                            BirthDate = new DateOnly(2022, 4, 16),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Name = "Eric",
                            WeightKg = 490.40205182859131
                        },
                        new
                        {
                            Id = 14,
                            AnimalTypeId = 3,
                            BirthDate = new DateOnly(2022, 10, 8),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Name = "Harold",
                            WeightKg = 58.376759228178244
                        },
                        new
                        {
                            Id = 15,
                            AnimalTypeId = 4,
                            BirthDate = new DateOnly(2024, 7, 28),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Name = "Noel",
                            WeightKg = 161.24928718487257
                        });
                });

            modelBuilder.Entity("API_Farm.Models.AnimalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("animal_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "vertebrados de sangre caliente con pelo o pelaje.",
                            Name = "mamífero"
                        },
                        new
                        {
                            Id = 2,
                            Description = "vertebrados emplumados y alados capaces de volar.",
                            Name = "ave"
                        },
                        new
                        {
                            Id = 3,
                            Description = "vertebrados de sangre fría con escamas.",
                            Name = "reptil"
                        },
                        new
                        {
                            Id = 4,
                            Description = "vertebrados de sangre fría que pasan parte de su vida en el agua y parte en tierra.",
                            Name = "anfibio"
                        },
                        new
                        {
                            Id = 5,
                            Description = "vertebrados acuáticos con branquias, aletas y escamas.",
                            Name = "pez"
                        },
                        new
                        {
                            Id = 6,
                            Description = "animales sin columna vertebral, incluyendo insectos, arañas y moluscos.",
                            Name = "invertebrado"
                        });
                });

            modelBuilder.Entity("API_Farm.Models.Animal", b =>
                {
                    b.HasOne("API_Farm.Models.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");
                });
#pragma warning restore 612, 618
        }
    }
}
